# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NeiHai' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NeiHai

  target 'NeiHaiTests' do
    inherit! :search_paths
    # Pods for testing

 pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 3.7.5'
  end

end
